# Bits to Decimal Converter
# The numbers form a geometric sequence where each term is generated by multiplying the previous term by 2, 
# expressed by the general formula (2 ^ n - 1)

def power(base, exponent):  #manual pow()
    result = 1
    for _ in range(exponent):
        result = result * base
    return result
def geometricSequence(n): # 16 8 4 2 1 [series code]
    return power(2, n - 1)

def bitsToDecimal(bits):
    res = 0
    for i, bit in enumerate(bits[::-1], start=1):
        res = geometricSequence(i) * int(bit)
    print(res)

def main():
    bits = "100"
    bitsToDecimal(bits)
    
    
if __name__ == "__main__":
    main()

'''
steps : series    bit
stp1 :    1     x  0  = 0
stp2 :    2     x  0  = 0
stp3 :    4     x  1  = 4
'''